org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=winterfall
mod_name=WinterFall
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.santipdr.winterfall
mod_authors=Santi-PdR
mod_description=WinterFall is a survival combat mod built for harsh scavenging, preparation, and escalating storms.
